customhost = "test-db-test.cxopzdwoz6ta.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Tanishka20.#$"
customdb = "testDB"
custombucket = "nagp-test-db-site"
customregion = "us-east-1"
